In [5]:
import pandas as pd
from sqlalchemy import create_engine

df_zones = pd.read_csv('taxi_zone_lookup.csv')
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [6]:

engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [7]:
df_zones.to_sql(name='zones', con=engine, if_exists='replace')

-1

In [9]:
df_zones.shape

(265, 4)

In [8]:
pd.read_sql('SELECT COUNT(*) FROM zones', con=engine)

   count
0    265